version: '3.8'
services:
  graphdb:
    container_name: graphdb
    image: khaller/graphdb-free:latest
    network_mode: host

  ot-node:
    build: 
      context: .
      dockerfile: Debian.Dockerfile
    depends_on:
      - graphdb
    expose:
      - 8900
      - 9000
    command: >
       bash -c "
        service mariadb start &&
        forever index.js                
        "
    volumes:
      - ${PWD}/.origintrail_noderc:/ot-node/.origintrail_noderc
      - ~/certs/:/root/certs/
    network_mode: host
    
