name: TEST-docker

on: [pull_request]
env:
  NODE_ENV: development
  ARTIFACTS_DIR: artifacts
  CUCUMBER_ARTIFACTS_DIR: artifacts/cucumber
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [9.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: mkdir -p $ARTIFACTS_DIR
      - run: sudo chmod -R 777 $ARTIFACTS_DIR
      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
      - run: sudo chmod -R 777 $CUCUMBER_ARTIFACTS_DIR
      - run: cp .origintrail_noderc.travis .origintrail_noderc
      - run: npm install
      - run: npm run ganache > $ARTIFACTS_DIR/ganache.log & npm run truffle:deploy:ganache > $ARTIFACTS_DIR/truffle-migrate.log;
      - run: ./test/docker/check_image.sh;
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-artifact
          path: /home/runner/work/ot-node/ot-node/artifacts
